# Generated by Django 3.0 on 2020-02-06 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('weather', models.CharField(choices=[('FG', '안개'), ('SW', '눈'), ('SY', '맑음'), ('RN', '비'), ('MD', '미세먼지'), ('CD', '구름'), ('NI', '관심없음')], default='NI', max_length=2, verbose_name='날씨')),
                ('title', models.CharField(max_length=20, verbose_name='제목')),
                ('Contents', models.TextField(verbose_name='내용')),
                ('realized', models.CharField(max_length=20, verbose_name='느낀점')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='작성날짜')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정날짜')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Diaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-author'],
            },
        ),
    ]
