# Generated by Django 3.0 on 2020-02-12 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-author'], 'verbose_name_plural': 'Diaries'},
        ),
    ]
