version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: sh -c "python diary-note/manage.py migrate && python diary-note/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db